spring:
  datasource:
    url: jdbc:postgresql://ec2-34-234-228-127.compute-1.amazonaws.com:5432/d1jguje8keilm8
    username: shgfgnathhvljm
    password: 75136d0bd28d46e9de699b752d183aa5d84296277525c8003f35fd9802859438

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


# Spring Security configuration

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 252890713656-6hkd4jl34l4qcm5cn022knbn3quru1be.apps.googleusercontent.com
            client-secret: mt8s9jUW9qmFCcOzzRKtj57l
     